

on:
  release:
    types: [published]

jobs:
  release-production:
    name: Release to Production
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Get Artifact from Release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: ${{ github.event.release.id }}
          file: cdk.out.zip
      - name: Unzip Artifact
        run: unzip cdk.out.zip
      - uses: actions/setup-node@v3
        with:
          node-version: v18.15.0
      - name: Authenticate Via OIDC Role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: us-east-1
          role-duration-seconds: 1800
          role-skip-session-tagging: true
          role-to-assume: ${{ secrets.ACTIONS_ROLE_ARN }}
      - name: Deploy - Prod
        run: |-
          npm install -g aws-cdk
          npx cdk deploy --app "./cdk.out/assembly-Prod" --never-approve